#!/usr/bin/env python3
"""Independent brute-force check of Chvátal's conjecture for small n.

Completely independent of enumerate.c and of the antichain reduction:
enumerates ALL ideals on [n] directly (as downward closures of arbitrary
antichains of nonempty sets), computes the TRUE maximum intersecting
subfamily size by exact max-clique (Bron-Kerbosch with pivoting) over the
intersection graph of the ideal's nonempty members, and compares it with the
maximum star size.  Any ideal with max_intersecting > max_star would be a
counterexample to Chvátal's conjecture.

Sanity anchor: the number of antichains of nonempty subsets of [n] must equal
Dedekind(n) - 1  (all monotone families except the one generated by {∅}):
n=3: 19, n=4: 167, n=5: 7580.
"""
import sys
from itertools import combinations

DEDEKIND_MINUS1 = {1: 2, 2: 5, 3: 19, 4: 167, 5: 7580}


def antichains(n):
    """All antichains of nonempty subsets of [n], as tuples of bitmasks."""
    nm = 1 << n
    masks = list(range(1, nm))

    def rec(chosen, cands):
        yield tuple(chosen)
        for i, s in enumerate(cands):
            nxt = [t for t in cands[i + 1:] if (t & s) != s and (t & s) != t]
            chosen.append(s)
            yield from rec(chosen, nxt)
            chosen.pop()

    yield from rec([], masks)


def down_closure(A):
    F = set()
    for a in A:
        t = a
        while True:
            F.add(t)
            if t == 0:
                break
            t = (t - 1) & a
    return F


def max_clique(verts, adj):
    """Exact maximum clique size, Bron-Kerbosch with pivot, bitset sets."""
    best = 0

    def bk(R_size, P, X):
        nonlocal best
        if P == 0 and X == 0:
            best = max(best, R_size)
            return
        if R_size + bin(P).count("1") <= best:
            return
        PX = P | X
        pivot = max(((bin(P & adj[v]).count("1"), v) for v in bits(PX)))[1]
        for v in bits(P & ~adj[pivot]):
            bk(R_size + 1, P & adj[v], X & adj[v])
            P &= ~(1 << v)
            X |= 1 << v

    def bits(b):
        while b:
            lo = b & -b
            yield lo.bit_length() - 1
            b ^= lo

    bk(0, (1 << len(verts)) - 1, 0)
    return best


def check(n):
    count = 0
    worst = -(10 ** 9)
    ties = 0
    viol = []
    for A in antichains(n):
        count += 1
        if not A:
            continue
        F = down_closure(A)
        members = sorted(F - {0})
        if not members:
            continue
        maxdeg = max(sum(1 for s in members if s >> x & 1) for x in range(n))
        idx = {s: i for i, s in enumerate(members)}
        adj = [0] * len(members)
        for i, s in enumerate(members):
            for j in range(i + 1, len(members)):
                if s & members[j]:
                    adj[i] |= 1 << j
                    adj[j] |= 1 << i
        mc = max_clique(members, adj)
        ex = mc - maxdeg
        if ex > worst:
            worst = ex
        if ex == 0:
            ties += 1
        if ex > 0:
            viol.append((A, mc, maxdeg))
            print(f"VIOLATION n={n} antichain={[format(a,'b') for a in A]} "
                  f"max_intersecting={mc} maxdeg={maxdeg}", flush=True)
    expected = DEDEKIND_MINUS1.get(n)
    ok = expected is None or count == expected
    print(f"n={n}: ideals={count} (expected {expected}, {'OK' if ok else 'MISMATCH'}) "
          f"max_excess={worst} ideals_with_nonstar_tie={ties} violations={len(viol)}",
          flush=True)
    return ok and not viol


if __name__ == "__main__":
    ns = [int(a) for a in sys.argv[1:]] or [3, 4, 5]
    allok = all([check(n) for n in ns])
    sys.exit(0 if allok else 1)
